DROP DATABASE IF EXISTS DBFIGURAGEOMETRICA;

CREATE DATABASE DBFIGURAGEOMETRICA;

USE DBFIGURAGEOMETRICA;

CREATE TABLE FIGURA (
	IDFIGURA INT NOT NULL PRIMARY KEY AUTO_INCREMENT
);

CREATE TABLE PROPRIEDADE (
	IDPROPRIEDADE INT NOT NULL PRIMARY KEY AUTO_INCREMENT
	, IDFIGURA INT NOT NULL
	, TAMANHO NUMERIC(8,2)
	, TIPO ENUM('RAIO', 'ARESTA', 'ALTURA', 'BASE')
	, FOREIGN KEY (IDFIGURA) REFERENCES FIGURA (IDFIGURA)
);

