SET GLOBAL log_bin_trust_function_creators = 1;

DROP DATABASE IF EXISTS DBFUNCOES;
CREATE DATABASE DBFUNCOES;
USE DBFUNCOES;

DELIMITER $$

CREATE FUNCTION FN_SOMA(N1 INT, N2 INT) RETURNS INT
BEGIN
	RETURN N1 + N2;
END $$

CREATE FUNCTION FN_SUBTRACAO(N1 INT, N2 INT) RETURNS INT
BEGIN
	RETURN N1 - N2;
END $$

CREATE FUNCTION FN_MULTIPLICACAO(N1 INT, N2 INT) RETURNS INT
BEGIN
	RETURN N1 * N2;
END $$

CREATE FUNCTION FN_DIVISAO(N1 INT, N2 INT) RETURNS NUMERIC(8,2)
BEGIN
	IF(N2 = 0) THEN
		SIGNAL SQLSTATE "45000" SET MESSAGE_TEXT = "IMPOSSÍVEL DIVIDIR POR ZERO"; 
    END IF;
	RETURN N1 / N2;
END $$

CREATE FUNCTION FN_CALCULADORA(N1 INT, N2 INT, OPERADOR CHAR(1)) RETURNS NUMERIC(8,2)
BEGIN
	CASE OPERADOR
		WHEN "+" THEN RETURN FN_SOMA(N1,N2);
        WHEN "-" THEN RETURN FN_SUBTRACAO(N1,N2);
        WHEN "*" THEN RETURN FN_MULTIPLICACAO(N1,N2);
        WHEN "/" THEN RETURN FN_DIVISAO(N1,N2);
        ELSE RETURN 0;
    END CASE;
END $$

CREATE FUNCTION FN_PRIMO(N INT) RETURNS TEXT
BEGIN
	DECLARE I INT;
    DECLARE DIVISORES INT;
    SET I = 1;
    SET DIVISORES = 0;

    WHILE(I <= N) DO
		IF(N % I = 0) THEN
			SET DIVISORES = DIVISORES + 1;
        END IF;
        SET I = I + 1;
    END WHILE;
    
    IF(DIVISORES = 2) THEN
		RETURN "É PRIMO!";
	ELSE
		RETURN "NÃO É PRIMO!";
	END IF;
END $$

CREATE FUNCTION FN_IDADE(NASCIMENTO DATE) RETURNS INT
BEGIN
	DECLARE IDADE INT;
    DECLARE HOJE DATE;
    SET HOJE = NOW();
    
	SET IDADE = YEAR(HOJE) - YEAR(NASCIMENTO);
    
    IF(MONTH(HOJE) <= MONTH(NASCIMENTO)) THEN
		IF(DAY(HOJE) < DAY(NASCIMENTO)) THEN
			SET IDADE = IDADE - 1;
		END IF;
    END IF;
    
    RETURN IDADE;
END $$

CREATE FUNCTION FN_NIVER(ANIVERSARIO DATE) RETURNS DATE
BEGIN
	DECLARE PROX_ANIVERSARIO DATE;
    DECLARE HOJE DATE;
    SET HOJE = NOW();
    SET PROX_ANIVERSARIO = CONCAT(YEAR(NOW()), "-", MONTH(ANIVERSARIO), "-", DAY(ANIVERSARIO));
    
    IF(ANIVERSARIO >= HOJE ) THEN
		SET PROX_ANIVERSARIO = CONCAT((YEAR(ANIVERSARIO) + 1), "-", MONTH(ANIVERSARIO), "-", DAY(ANIVERSARIO));
    END IF;
    
    RETURN PROX_ANIVERSARIO;
END $$

CREATE FUNCTION FN_ROMANO(N INT) RETURNS TEXT
BEGIN
	
    DECLARE ALGARISMO TEXT;
    DECLARE NUM INT;
    SET ALGARISMO = "";
    SET NUM = N;
    
	-- NÚMERO DE 1 A 4999
    IF(N <= 0 OR N > 4999) THEN
		RETURN N;
    END IF;
    
    WHILE((NUM / 1000) >= 1) DO
		SET ALGARISMO = CONCAT(ALGARISMO, "M");
        SET NUM = NUM - 1000; 
    END WHILE;
    
    IF((NUM / 900) >= 1) THEN
		SET ALGARISMO = CONCAT(ALGARISMO, "CM");
        SET NUM = NUM - 900;
    END IF;
    
    IF((NUM / 500) >= 1) THEN
		SET ALGARISMO = CONCAT(ALGARISMO, "D");
        SET NUM = NUM - 500;
    END IF;
    
    IF((NUM / 400) >= 1) THEN
		SET ALGARISMO = CONCAT(ALGARISMO, "CD");
        SET NUM = NUM - 400;
    END IF;
    
    WHILE((NUM / 100) >= 1) DO
		SET ALGARISMO = CONCAT(ALGARISMO, "C");
        SET NUM = NUM - 100;
    END WHILE;
    
    IF((NUM / 90) >= 1) THEN
		SET ALGARISMO = CONCAT(ALGARISMO, "XC");
        SET NUM = NUM - 90;
    END IF;
    
    IF((NUM / 50) >= 1) THEN
		SET ALGARISMO = CONCAT(ALGARISMO, "L");
        SET NUM = NUM - 50;
    END IF;
    
    IF((NUM / 40) >= 1) THEN
		SET ALGARISMO = CONCAT(ALGARISMO, "XL");
        SET NUM = NUM - 40;
    END IF;
    
    WHILE((NUM / 10) >= 1) DO
		SET ALGARISMO = CONCAT(ALGARISMO, "X");
        SET NUM = NUM - 10;
    END WHILE;
    
     IF((NUM / 9) >= 1) THEN
		SET ALGARISMO = CONCAT(ALGARISMO, "IV");
        SET NUM = NUM - 9;
    END IF;
    
    IF((NUM / 5) >= 1) THEN
		SET ALGARISMO = CONCAT(ALGARISMO, "V");
        SET NUM = NUM - 5;
    END IF;
    
    IF((NUM / 4) >= 1) THEN
		SET ALGARISMO = CONCAT(ALGARISMO, "IV");
        SET NUM = NUM - 4;
    END IF;
    
    WHILE(NUM >= 1) DO
		SET ALGARISMO = CONCAT(ALGARISMO, "I");
        SET NUM = NUM - 1;
    END WHILE;
    
    RETURN ALGARISMO;
END $$

CREATE FUNCTION FN_EXTENSO(N INT) RETURNS TEXT
BEGIN
    DECLARE EXTENSO TEXT;
    SET EXTENSO = "";
    
    IF(N < 0 OR N > 999) THEN
		RETURN "NÚMERO INVÁLIDO!";
    END IF;
    
    IF(N <= 999 AND N >= 900) THEN
		SET EXTENSO = CONCAT(EXTENSO, "NOVECENTOS");
        SET N = N - 900;
    END IF;
    IF(N >= 800 AND N < 900) THEN
		SET EXTENSO = CONCAT(EXTENSO, "OITOCENTOS");
        SET N = N - 800;
    END IF;
    IF(N >= 700 AND N < 800) THEN
		SET EXTENSO = CONCAT(EXTENSO, "SETECENTOS");
        SET N = N - 700;
    END IF;
    IF(N >= 600 AND N < 700) THEN
		SET EXTENSO = CONCAT(EXTENSO, "SEISCENTOS");
        SET N = N - 600;
    END IF;
    IF(N >= 500 AND N < 600) THEN
		SET EXTENSO = CONCAT(EXTENSO, "QUINHENTOS");
        SET N = N - 500;
    END IF;
    IF(N >= 400 AND N < 500) THEN
		SET EXTENSO = CONCAT(EXTENSO, "QUATROCENTOS");
        SET N = N - 400;
    END IF;
    IF(N >= 300 AND N < 400) THEN
		SET EXTENSO = CONCAT(EXTENSO, "TREZENTOS");
        SET N = N - 300;
    END IF;
    IF(N >= 200 AND N < 300) THEN
		SET EXTENSO = CONCAT(EXTENSO, "DUZENTOS");
        SET N = N - 200;
    END IF;
    IF(N > 100 AND N < 200) THEN
		SET EXTENSO = CONCAT(EXTENSO, "CENTO");
        SET N = N - 100;
    END IF;
    IF(N = 100) THEN
		SET EXTENSO = CONCAT(EXTENSO, "CEM");
        SET N = N - 100;
    END IF;
    
    IF(N >= 90 AND N <= 99) THEN
		IF(EXTENSO <> "") THEN
			SET EXTENSO = CONCAT(EXTENSO, " E ");
        END IF;
		SET EXTENSO = CONCAT(EXTENSO, "NOVENTA");
        SET N = N - 90;
    END IF;
    IF(N >= 80 AND N <= 89) THEN
		IF(EXTENSO <> "") THEN
			SET EXTENSO = CONCAT(EXTENSO, " E ");
        END IF;
		SET EXTENSO = CONCAT(EXTENSO, "OITENTA");
        SET N = N - 80;
    END IF;
    IF(N >= 70 AND N <= 79) THEN
		IF(EXTENSO <> "") THEN
			SET EXTENSO = CONCAT(EXTENSO, " E ");
        END IF;
		SET EXTENSO = CONCAT(EXTENSO, "SETENTA");
        SET N = N - 70;
    END IF;
    IF(N >= 60 AND N <= 69) THEN
		IF(EXTENSO <> "") THEN
			SET EXTENSO = CONCAT(EXTENSO, " E ");
        END IF;
		SET EXTENSO = CONCAT(EXTENSO, "SESSENTA");
        SET N = N - 60;
    END IF;
    IF(N >= 50 AND N <= 59) THEN
		IF(EXTENSO <> "") THEN
			SET EXTENSO = CONCAT(EXTENSO, " E ");
        END IF;
		SET EXTENSO = CONCAT(EXTENSO, "CINQUENTA");
        SET N = N - 50;
    END IF;
    IF(N >= 40 AND N <= 49) THEN
		IF(EXTENSO <> "") THEN
			SET EXTENSO = CONCAT(EXTENSO, " E ");
        END IF;
		SET EXTENSO = CONCAT(EXTENSO, "QUARENTA");
        SET N = N - 40;
    END IF;
    IF(N >= 30 AND N <= 39) THEN
		IF(EXTENSO <> "") THEN
			SET EXTENSO = CONCAT(EXTENSO, " E ");
        END IF;
		SET EXTENSO = CONCAT(EXTENSO, "TRINTA");
        SET N = N - 30;
    END IF;
    IF(N >= 20 AND N <= 29) THEN
		IF(EXTENSO <> "") THEN
			SET EXTENSO = CONCAT(EXTENSO, " E ");
        END IF;
		SET EXTENSO = CONCAT(EXTENSO, "VINTE");
        SET N = N - 20;
    END IF;
    
    IF(N = 19) THEN
		IF(EXTENSO <> "") THEN
			SET EXTENSO = CONCAT(EXTENSO, " E ");
        END IF;
		SET EXTENSO = CONCAT(EXTENSO, "DEZENOVE");
        SET N = N - 19;
    END IF;
    IF(N = 18) THEN
		IF(EXTENSO <> "") THEN
			SET EXTENSO = CONCAT(EXTENSO, " E ");
        END IF;
		SET EXTENSO = CONCAT(EXTENSO, "DEZOITO");
        SET N = N - 18;
    END IF;
    IF(N = 17) THEN
		IF(EXTENSO <> "") THEN
			SET EXTENSO = CONCAT(EXTENSO, " E ");
        END IF;
		SET EXTENSO = CONCAT(EXTENSO, "DEZESSETE");
        SET N = N - 17;
    END IF;
    IF(N = 16) THEN
		IF(EXTENSO <> "") THEN
			SET EXTENSO = CONCAT(EXTENSO, " E ");
        END IF;
		SET EXTENSO = CONCAT(EXTENSO, "DEZESSEIS");
        SET N = N - 16;
    END IF;
    IF(N = 15) THEN
		IF(EXTENSO <> "") THEN
			SET EXTENSO = CONCAT(EXTENSO, " E ");
        END IF;
		SET EXTENSO = CONCAT(EXTENSO, "QUINZE");
        SET N = N - 15;
    END IF;
    IF(N = 14) THEN
		IF(EXTENSO <> "") THEN
			SET EXTENSO = CONCAT(EXTENSO, " E ");
        END IF;
		SET EXTENSO = CONCAT(EXTENSO, "QUATORZE");
        SET N = N - 14;
    END IF;
    IF(N = 13) THEN
		IF(EXTENSO <> "") THEN
			SET EXTENSO = CONCAT(EXTENSO, " E ");
        END IF;
		SET EXTENSO = CONCAT(EXTENSO, "TREZE");
        SET N = N - 13;
    END IF;
    IF(N = 12) THEN
		IF(EXTENSO <> "") THEN
			SET EXTENSO = CONCAT(EXTENSO, " E ");
        END IF;
		SET EXTENSO = CONCAT(EXTENSO, "DOZE");
        SET N = N - 12;
    END IF;
    IF(N = 10) THEN
		IF(EXTENSO <> "") THEN
			SET EXTENSO = CONCAT(EXTENSO, " E ");
        END IF;
		SET EXTENSO = CONCAT(EXTENSO, "DEZ");
        SET N = N - 10;
    END IF;
    IF(N = 9) THEN
		IF(EXTENSO <> "") THEN
			SET EXTENSO = CONCAT(EXTENSO, " E ");
        END IF;
		SET EXTENSO = CONCAT(EXTENSO, "NOVE");
        SET N = N - 9;
    END IF;
    IF(N = 8) THEN
		IF(EXTENSO <> "") THEN
			SET EXTENSO = CONCAT(EXTENSO, " E ");
        END IF;
		SET EXTENSO = CONCAT(EXTENSO, "OITO");
        SET N = N - 8;
    END IF;
    IF(N = 7) THEN
		IF(EXTENSO <> "") THEN
			SET EXTENSO = CONCAT(EXTENSO, " E ");
        END IF;
		SET EXTENSO = CONCAT(EXTENSO, "SETE");
        SET N = N - 7;
    END IF;
    IF(N = 6) THEN
		IF(EXTENSO <> "") THEN
			SET EXTENSO = CONCAT(EXTENSO, " E ");
        END IF;
		SET EXTENSO = CONCAT(EXTENSO, "SEIS");
        SET N = N - 6;
    END IF;
    IF(N = 5) THEN
		IF(EXTENSO <> "") THEN
			SET EXTENSO = CONCAT(EXTENSO, " E ");
        END IF;
		SET EXTENSO = CONCAT(EXTENSO, "CINCO");
        SET N = N - 5;
    END IF;
    IF(N = 4) THEN
		IF(EXTENSO <> "") THEN
			SET EXTENSO = CONCAT(EXTENSO, " E ");
        END IF;
		SET EXTENSO = CONCAT(EXTENSO, "QUATRO");
        SET N = N - 4;
    END IF;
    IF(N = 3) THEN
		IF(EXTENSO <> "") THEN
			SET EXTENSO = CONCAT(EXTENSO, " E ");
        END IF;
		SET EXTENSO = CONCAT(EXTENSO, "TRÊS");
        SET N = N - 3;
    END IF;
    IF(N = 2) THEN
		IF(EXTENSO <> "") THEN
			SET EXTENSO = CONCAT(EXTENSO, " E ");
        END IF;
		SET EXTENSO = CONCAT(EXTENSO, "DOIS");
        SET N = N - 2;
    END IF;
    IF(N = 1) THEN
		IF(EXTENSO <> "") THEN
			SET EXTENSO = CONCAT(EXTENSO, " E ");
        END IF;
		SET EXTENSO = CONCAT(EXTENSO, "UM");
        SET N = N - 1;
    END IF;
    IF(N = 0) THEN
		IF(EXTENSO = "") THEN
			SET EXTENSO = CONCAT(EXTENSO, "ZERO");
        END IF;
    END IF;
    
    RETURN EXTENSO;
END $$

DELIMITER ;

-- TESTANDO AS FUNÇÕES

-- CALCULADORA (+ SOMA, - SUB, * MULT, / DIV)
-- SELECT FN_CALCULADORA(5,5,"*"); /* 5 x 5 */

-- NÚMERO PRIMO
-- SELECT FN_PRIMO(10); /* TESTANDO SE DEZ É PRIMO */

-- IDADE
-- SELECT FN_IDADE("1991-11-29"); /* RETORNANDO A IDADE DE QUEM NASCEU EM 29/11/1991 */

-- PRÓXIMO ANIVERSÁRIO
-- SELECT FN_NIVER("1991-11-29"); /* RETORNANDO A DATA DO PRÓXIMO ANIVERSÁRIO DE QUEM NASCEU EM 29/11/1991 */

-- NÚMERO ROMANO (DE 1 A 4999)
-- SELECT FN_ROMANO(3255); /* RETORNA 3255 EM ALGARISMO ROMANO */

-- NÚMERO POR EXTENSO (0 A 999)
-- SELECT FN_EXTENSO(857); /* RETORNA 857 POR EXTENSO */