DROP DATABASE IF EXISTS DBQUIZ;

CREATE DATABASE DBQUIZ;

USE DBQUIZ;

CREATE TABLE QUIZ(
	IDQUIZ INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TITULO VARCHAR(100),
	DESCRICAO VARCHAR(100),
	TIPO ENUM('PESQUISA','TESTE')
);

CREATE TABLE PERGUNTA(
	IDPERGUNTA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	IDQUIZ INT NOT NULL,
	ENUNCIADO VARCHAR(100),
	DTINICIAL DATETIME,
	DTFINAL DATETIME,
	CONSTRAINT FK_PERGUNTA_QUIZ FOREIGN KEY (IDQUIZ) REFERENCES QUIZ(IDQUIZ)
);

CREATE TABLE OPCAO(
	IDOPCAO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	IDPERGUNTA INT NOT NULL,
	TEXTO VARCHAR(100),
	CERTA ENUM('SIM','NÃO','INDEFINIDO'),
	CONSTRAINT FK_OPCAO_PERGUNTA FOREIGN KEY (IDPERGUNTA) REFERENCES PERGUNTA(IDPERGUNTA)
);

CREATE TABLE PARTICIPANTE(
	IDPARTICIPANTE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(100),
	EMAIL VARCHAR(100)
);

CREATE TABLE RESPOSTA(
	IDPARTICIPANTE INT NOT NULL,
	IDPERGUNTA INT NOT NULL,
	IDOPCAO INT NOT NULL,
	DTRESPOSTA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT PK_RESPOSTA PRIMARY KEY (IDPARTICIPANTE, IDPERGUNTA),
	CONSTRAINT FK_RESPOSTA_PARTICIPANTE FOREIGN KEY (IDPARTICIPANTE) REFERENCES PARTICIPANTE(IDPARTICIPANTE),
	CONSTRAINT FK_RESPOSTA_PERGUNTA FOREIGN KEY (IDPERGUNTA) REFERENCES PERGUNTA(IDPERGUNTA),
	CONSTRAINT FK_RESPOSTA_OPCAO FOREIGN KEY (IDOPCAO) REFERENCES OPCAO(IDOPCAO)
);


DELIMITER $$
CREATE TRIGGER TR_OPCAO_BEFORE_INSERT BEFORE INSERT ON OPCAO FOR EACH ROW
BEGIN

	DECLARE TIPO ENUM('PESQUISA','TESTE');
	DECLARE QTDE INT DEFAULT 0;

	SELECT DISTINCT QUIZ.TIPO INTO TIPO FROM QUIZ INNER JOIN PERGUNTA ON PERGUNTA.IDQUIZ = QUIZ.IDQUIZ WHERE PERGUNTA.IDPERGUNTA = NEW.IDPERGUNTA;

	IF (TIPO = 'PESQUISA' AND NEW.CERTA IN ('SIM','NÃO') ) THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'A OPÇÃO INFORMADA NÃO É VALIDA PARA QUIZ DE PESQUISA DE PREFERENCIA';
	END IF;

	IF (TIPO <> 'PESQUISA' AND NEW.CERTA IN ('INDEFINIDO') ) THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'A OPÇÃO INFORMADA NÃO É VALIDA PARA QUIZ DE TESTE DE CONHECIMENTO';
	END IF;

	SELECT COUNT(OPCAO.IDOPCAO) INTO QTDE FROM OPCAO WHERE IDPERGUNTA = NEW.IDPERGUNTA AND CERTA = 'SIM';

	IF (TIPO = 'TESTE' AND NEW.CERTA IN ('SIM') and QTDE > 0) THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'JÁ EXISTE UMA OPÇÃO CERTA INFORMADA PARA ESTE QUIZ DE TESTE DE CONHECIMENTO';
	END IF;

END$$

DELIMITER ;



DELIMITER $$
CREATE TRIGGER TR_OPCAO_BEFORE_UPDATE BEFORE UPDATE ON OPCAO FOR EACH ROW
BEGIN

	DECLARE TIPO ENUM('PESQUISA','TESTE');
	DECLARE QTDE INT DEFAULT 0;

	SELECT DISTINCT QUIZ.TIPO INTO TIPO FROM QUIZ INNER JOIN PERGUNTA ON PERGUNTA.IDQUIZ = QUIZ.IDQUIZ WHERE PERGUNTA.IDPERGUNTA = NEW.IDPERGUNTA;

	IF (TIPO = 'PESQUISA' AND NEW.CERTA IN ('SIM','NÃO') ) THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'A OPÇÃO INFORMADA NÃO É VALIDA PARA QUIZ DE PESQUISA DE PREFERENCIA';
	END IF;

	IF (TIPO <> 'PESQUISA' AND NEW.CERTA IN ('INDEFINIDO') ) THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'A OPÇÃO INFORMADA NÃO É VALIDA PARA QUIZ DE TESTE DE CONHECIMENTO';
	END IF;

	SELECT COUNT(OPCAO.IDOPCAO) INTO QTDE FROM OPCAO WHERE IDPERGUNTA = NEW.IDPERGUNTA AND CERTA = 'SIM' AND IDOPCAO <> NEW.IDOPCAO;

	IF (TIPO = 'TESTE' AND NEW.CERTA IN ('SIM') and QTDE > 0) THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'JÁ EXISTE UMA OPÇÃO CERTA INFORMADA PARA ESTE QUIZ DE TESTE DE CONHECIMENTO';
	END IF;

END$$

DELIMITER ;


USE DBQUIZ;

INSERT INTO QUIZ(TITULO, DESCRICAO, TIPO)VALUES('Pesquisa para ver qual é a melhor torcida', 'Pesquisa de preferência', 'TESTE');
INSERT INTO QUIZ(TITULO, DESCRICAO, TIPO)VALUES('Pesquisa para escolher a melhor cidade', 'Pesquisa de preferência', 'PESQUISA');
INSERT INTO QUIZ(TITULO, DESCRICAO, TIPO)VALUES('Teste seus conhecimentos sobre Santa Catarina', 'Teste de conhecimento', 'TESTE');

INSERT INTO PERGUNTA(IDQUIZ, ENUNCIADO, DTINICIAl, DTFINAL)VALUES(1, 'Qual é o melhor time do Brasil', '2013-04-10', '2013-11-10');
INSERT INTO PERGUNTA(IDQUIZ, ENUNCIADO, DTINICIAL, DTFINAL)VALUES(3, 'Qual a capital de Santa Catarina', '2013-01-01', '2014-01-01');
INSERT INTO PERGUNTA(IDQUIZ, ENUNCIADO, DTINICIAL, DTFINAL)VALUES(2, 'Qual é a melhor cidade de Santa Catarina', '2013-10-01', '2013-10-31');
INSERT INTO PERGUNTA(IDQUIZ, ENUNCIADO, DTINICIAL, DTFINAL)VALUES(1, 'Qual a melhor praia de Florianópolis', '2013-01-12', '2014-05-31');


INSERT INTO OPCAO(IDPERGUNTA, TEXTO, CERTA)VALUES(1, 'AVAÍ', 'NÃO');
INSERT INTO OPCAO(IDPERGUNTA, TEXTO, CERTA)VALUES(1, 'CORITIBA', 'NÃO');
INSERT INTO OPCAO(IDPERGUNTA, TEXTO, CERTA)VALUES(1, 'SÃO PAULO', 'NÃO');
INSERT INTO OPCAO(IDPERGUNTA, TEXTO, CERTA)VALUES(1, 'PALMEIRAS', 'NÃO');
INSERT INTO OPCAO(IDPERGUNTA, TEXTO, CERTA)VALUES(1, 'CORINTIANS', 'NÃO');
INSERT INTO OPCAO(IDPERGUNTA, TEXTO, CERTA)VALUES(1, 'FLAMENGO', 'NÃO');
INSERT INTO OPCAO(IDPERGUNTA, TEXTO, CERTA)VALUES(1, 'ÍBIS', 'SIM');
INSERT INTO OPCAO(IDPERGUNTA, TEXTO, CERTA)VALUES(2, 'BLUMENAU', 'NÃO');
INSERT INTO OPCAO(IDPERGUNTA, TEXTO, CERTA)VALUES(2, 'FLORIANOPOLIS', 'SIM');
INSERT INTO OPCAO(IDPERGUNTA, TEXTO, CERTA)VALUES(2, 'SÃO JOSÉ', 'NÃO');
INSERT INTO OPCAO(IDPERGUNTA, TEXTO, CERTA)VALUES(3, 'BLUMENAU', 'INDEFINIDO');
INSERT INTO OPCAO(IDPERGUNTA, TEXTO, CERTA)VALUES(3, 'FLORIANÓPOLIS', 'INDEFINIDO');
INSERT INTO OPCAO(IDPERGUNTA, TEXTO, CERTA)VALUES(3, 'CHAPECO', 'INDEFINIDO');
INSERT INTO OPCAO(IDPERGUNTA, TEXTO, CERTA)VALUES(4, 'JURERE', 'NÃO');
INSERT INTO OPCAO(IDPERGUNTA, TEXTO, CERTA)VALUES(4, 'CANASVIEIRA', 'NÃO');
INSERT INTO OPCAO(IDPERGUNTA, TEXTO, CERTA)VALUES(4, 'PRAIA DO MOLE', 'NÃO');
INSERT INTO OPCAO(IDPERGUNTA, TEXTO, CERTA)VALUES(4, 'JOAQUINA', 'SIM');

INSERT INTO PARTICIPANTE(NOME, EMAIL)VALUES('MARIA', 'MARIA@QUIZ.COM');
INSERT INTO PARTICIPANTE(NOME, EMAIL)VALUES('JOAO', 'JOAOQUIZ.COM');
INSERT INTO PARTICIPANTE(NOME, EMAIL)VALUES('PAULO', 'PAULO@QUIZ.COM');

INSERT INTO RESPOSTA(IDPARTICIPANTE, IDPERGUNTA, IDOPCAO, DTRESPOSTA)VALUES(1, 1, 2, '2013-10-12');
INSERT INTO RESPOSTA(IDPARTICIPANTE, IDPERGUNTA, IDOPCAO, DTRESPOSTA)VALUES(1, 2, 2, '2013-10-12');
INSERT INTO RESPOSTA(IDPARTICIPANTE, IDPERGUNTA, IDOPCAO, DTRESPOSTA)VALUES(2, 1, 8, '2013-10-12');
INSERT INTO RESPOSTA(IDPARTICIPANTE, IDPERGUNTA, IDOPCAO, DTRESPOSTA)VALUES(3, 4, 16, '2013-10-12');