/*

Nesta atividade você deve programar o banco de dados da seguinte forma: quando for cadastrada 
uma venda, deve ser acessado a tabela de produto e pegar o valor atual do produto, trazendo esse 
valor para a venda. Também acessar a tabela cotação e converter o valor do produto de acordo com 
a cotação do dia, caso não tenha uma cotação para o dia o banco de dados não deve permitir o 
cadastro da venda.

*/

/*
QUESTÃO:
1. SÓ PODE INCLUIR VENDA, SE TIVER COTAÇÃO PARA A DATA DA VENDA

2. QUANDO UM PRODUTO FOR INCLUÍDO OU ALTERADO O VALOR DO PRODUTO 
EM DÓLAR CALCULADO COM BASE NA COTAÇÃO, PARA LOCALIZAR A COTAÇÃO COMPARE A DATA DE VENDA COM A DATA DA COTACAO;
*/

DROP DATABASE IF EXISTS DBCOTACAO;
CREATE DATABASE DBCOTACAO;
USE DBCOTACAO;

CREATE TABLE COTACAO (
	IDCOTACAO INT NOT NULL AUTO_INCREMENT
    , DTCOTACAO DATE
    , VALOR NUMERIC(8,2)
    , PRIMARY KEY (IDCOTACAO)
);

CREATE TABLE PRODUTO (
	IDPRODUTO INT NOT NULL AUTO_INCREMENT
    , NOME VARCHAR(45)
    , VALOR NUMERIC(8,2)
    , PRIMARY KEY(IDPRODUTO)
);

CREATE TABLE VENDA (
	IDVENDA INT NOT NULL AUTO_INCREMENT
    , IDPRODUTO INT NOT NULL
    , DTVENDA DATE
    , VALOR_REAL NUMERIC(8,2)
    , VALOR_DOLAR NUMERIC(8,2)
    , PRIMARY KEY (IDVENDA)
    , FOREIGN KEY (IDPRODUTO) REFERENCES PRODUTO (IDPRODUTO)
    );

INSERT INTO PRODUTO (NOME, VALOR)VALUES('CELULAR', 200);
INSERT INTO PRODUTO (NOME, VALOR)VALUES('TABLET', 350);

INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL -5 DAY)), 4.09 - 0.55);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL -4 DAY)), 4.09 - 0.45);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL -3 DAY)), 4.09 - 0.35);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL -2 DAY)), 4.09 - 0.25);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL -1 DAY)), 4.09 - 0.15);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL  0 DAY)), 4.09 - 0.05);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL  1 DAY)), 4.09 + 0.15);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL  2 DAY)), 4.09 + 0.25);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL  3 DAY)), 4.09 + 0.35);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL  4 DAY)), 4.09 + 0.45);
INSERT COTACAO(DTCOTACAO, VALOR)VALUES(DATE(DATE_ADD(NOW(), INTERVAL  5 DAY)), 4.09 + 0.55);

DELIMITER $$

CREATE TRIGGER TR_VENDA BEFORE INSERT ON VENDA FOR EACH ROW
BEGIN
	
    -- DECLARANDO VARIÁVEIS
    DECLARE VALOR_REAL NUMERIC(8,2);
    DECLARE DATA_COTACAO DATE;
    DECLARE VALOR_COTACAO NUMERIC(8,2);
    DECLARE VALOR_DOLAR NUMERIC(8,2);
    
	-- VERIFICANDO DATA DA COTAÇÃO
    SELECT DTCOTACAO INTO DATA_COTACAO FROM COTACAO WHERE DTCOTACAO = NEW.DTVENDA;
    
    IF (DATA_COTACAO IS NULL) THEN
		SIGNAL SQLSTATE "45000" SET MESSAGE_TEXT = "DATA PARA ESTA COTAÇÃO NÃO EXISTE";
	END IF;
    
    -- PEGANDO O VALOR EM REAIS
    SELECT VALOR INTO VALOR_REAL FROM PRODUTO WHERE PRODUTO.IDPRODUTO = NEW.IDPRODUTO;
    
    -- PEGANDO VALOR DA COTAÇÃO 
    SELECT VALOR INTO VALOR_COTACAO FROM COTACAO WHERE DTCOTACAO = NEW.DTVENDA;
    
    -- CALCULANDO VALOR DO DÓLAR
    SET VALOR_DOLAR = VALOR_REAL / VALOR_COTACAO;
    
    -- ALTERANDO OS DADOS
    SET NEW.VALOR_REAL = VALOR_REAL;
    SET NEW.VALOR_DOLAR = VALOR_DOLAR;

END $$

CREATE TRIGGER TR_VENDA_UP BEFORE UPDATE ON VENDA FOR EACH ROW
BEGIN
	
    -- DECLARANDO VARIÁVEIS
    DECLARE VALOR_REAL NUMERIC(8,2);
    DECLARE DATA_COTACAO DATE;
    DECLARE VALOR_COTACAO NUMERIC(8,2);
    DECLARE VALOR_DOLAR NUMERIC(8,2);
    
	-- VERIFICANDO DATA DA COTAÇÃO
    SELECT DTCOTACAO INTO DATA_COTACAO FROM COTACAO WHERE DTCOTACAO = NEW.DTVENDA;
    
    IF (DATA_COTACAO IS NULL) THEN
		SIGNAL SQLSTATE "45000" SET MESSAGE_TEXT = "DATA PARA ESTA COTAÇÃO NÃO EXISTE";
	END IF;
    
    -- PEGANDO O VALOR EM REAIS
    SELECT VALOR INTO VALOR_REAL FROM PRODUTO WHERE PRODUTO.IDPRODUTO = NEW.IDPRODUTO;
    
    -- PEGANDO VALOR DA COTAÇÃO 
    SELECT VALOR INTO VALOR_COTACAO FROM COTACAO WHERE DTCOTACAO = NEW.DTVENDA;
    
    -- CALCULANDO VALOR DO DÓLAR
    SET VALOR_DOLAR = VALOR_REAL / VALOR_COTACAO;
    
    -- ALTERANDO OS DADOS
    SET NEW.VALOR_REAL = VALOR_REAL;
    SET NEW.VALOR_DOLAR = VALOR_DOLAR;

END $$

DELIMITER ;

-- TESTES
INSERT INTO VENDA VALUES (NULL, 2, "2020-03-28", 100, 100);
INSERT INTO VENDA VALUES (NULL, 1, "2020-03-30", 100, 100);
INSERT INTO VENDA VALUES (NULL, 2, "2020-03-31", 100, 100);
INSERT INTO VENDA VALUES (NULL, 1, "2020-03-29", 100, 100);
-- DATA INEXISTENTE
INSERT INTO VENDA VALUES (NULL, 2, "2020-03-20", 100, 100);