/*
	ALUNO: GUILHERME VALMIR DE ANDRADE
*/

USE DBCONDOMINIO;

-- QUESTÃO 1 - CRIE UMA CONSULTA SQL QUE LISTE A QUANTIDADE DE MORADORES, MÉDIA
-- DA IDADE AGRUPADOR POR SEXO
SELECT 	COUNT(MORADOR.IDPESSOA) AS MORADOR,
		AVG( PESSOA.IDADE ) AS MEDIA_IDADE,
        PESSOA.SEXO AS SEXO
FROM MORADOR
INNER JOIN PESSOA ON 
(MORADOR.IDPESSOA = PESSOA.IDPESSOA)
GROUP BY SEXO;

-- QUESTÃO 2 - CRIE UMA CONSULTA SQL QUE LISTE A QUANTIDADE DE ANDARES POR
-- CONDOMÍNIO, ORDENADO PELA QUANTIDADE DE ANDARES DE FORMA DECRESCENTE.
-- LISTE O CÓDIGO IDENTIDICADOR DO CONDOMÍNIO, NOME DO CONDOMÍNIO
SELECT 	CONDOMINIO.IDCONDOMINIO AS CODIGO_CONDOMINIO,
		CONDOMINIO.NOME AS NOME_CONDOMINIO,
        COUNT(APARTAMENTO.ANDAR) AS ANDARES
FROM APARTAMENTO
INNER JOIN BLOCO ON 
(APARTAMENTO.IDBLOCO = BLOCO.IDBLOCO) 
INNER JOIN CONDOMINIO ON 
(BLOCO.IDCONDOMINIO = CONDOMINIO.IDCONDOMINIO)
GROUP BY CODIGO_CONDOMINIO, NOME_CONDOMINIO
ORDER BY ANDARES DESC;

-- QUESTÃO 3 - CRIE UMA CONSULTA SQL QUE LISTE A QUANTIDADE DE VISITA POR DIA DA
-- SEMANA ORDENADO PELA MAIOR QUANTIDADE. LISTE O DIA DA SEMANA (USE A FUNÇÃO
-- DAYOFWEEK) E A QUANTIDADE DE VISITAS
SELECT 	CASE DAYOFWEEK(VISITANTE.DTVISITA)
		WHEN 1 THEN "DOMINGO"
        WHEN 2 THEN "TERÇA"
        WHEN 3 THEN "QUARTA"
        WHEN 4 THEN "QUINTA"
        WHEN 5 THEN "SEXTA" 
        WHEN 6 THEN "SÁBADO" 
        ELSE "DOMINGO"
		END AS DIA_SEMANA,
		COUNT(VISITANTE.IDVISITANTE) AS QTDE_VISITA
FROM VISITANTE
GROUP BY DIA_SEMANA
ORDER BY QTDE_VISITA DESC;

-- QUESTÃO 4 - CRIE UMA CONSULTA SQL QUE LISTE O TAMANHO MÉDIO DOS
-- APARTAMENTOS POR CONDOMÍNIO. LISTE O CÓDIGO IDENTIDICADOR DO CONDOMÍNIO,
-- NOME DO CONDOMÍNIO E A QUANTIDADE DE APARTAMENTOS, A MÉDIA DO TAMANHO DOS
-- APARTAMENTOS E A QUANTIDADE MÉDIA DE MORADORES
SELECT 	CONDOMINIO.IDCONDOMINIO AS CODIGO_CONDOMINIO,
		CONDOMINIO.NOME AS CONDOMINIO,
        COUNT(APARTAMENTO.IDAPARTAMENTO) AS QTDE_APARTAMENTOS,
        AVG(APARTAMENTO.TAMANHO) AS MEDIA_TAMANHO,
        AVG( APARTAMENTO.IDAPARTAMENTO ) AS MEDIA_MORADORES
FROM APARTAMENTO
INNER JOIN BLOCO ON 
(APARTAMENTO.IDBLOCO = BLOCO.IDBLOCO) 
INNER JOIN CONDOMINIO ON 
(BLOCO.IDCONDOMINIO = CONDOMINIO.IDCONDOMINIO)
GROUP BY CODIGO_CONDOMINIO, CONDOMINIO;