SET SQL_SAFE_UPDATES = 0;
DROP DATABASE IF EXISTS DBMATRICULA;
CREATE DATABASE DBMATRICULA;
USE DBMATRICULA;

CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL AUTO_INCREMENT
	, NOME VARCHAR(45)
    , PRIMARY KEY (IDALUNO)
);

CREATE TABLE DISCIPLINA(	
	IDDISCIPLINA INT NOT NULL AUTO_INCREMENT
	, NOME VARCHAR(45)
	, DT_INICIO DATE
	, DT_FIM DATE
    , PRIMARY KEY (IDDISCIPLINA)
);

CREATE TABLE MATRICULA (
	IDALUNO INT NOT NULL
	, IDMATRICULA INT NOT NULL
    , IDDISCIPLINA INT NOT NULL
	, DT_MATRICULA DATE
    , PRIMARY KEY (IDALUNO, IDMATRICULA)
    , FOREIGN KEY (IDALUNO) REFERENCES ALUNO (IDALUNO)
    , FOREIGN KEY (IDDISCIPLINA) REFERENCES DISCIPLINA (IDDISCIPLINA)
);

/*
Regra:
O CAMPO DT_MATRICULA DEVE SER PREENCHIDO NO MOMENTO DO INSERT
O campo DT_MATRICULA NÃO PODE SER MENOR QUE DT_FIM DA DISCIPLINA
O CAMPO DT_FIM DA DISCIPLINA NÃO PODE SER MENOR QUE DT_INICIO DA DISCIPLINA
CASO JA TENHA ALUNO MATRICULA A DT_INICIO E DT_FIM NÃO PODE SER ALTERADO;
*/